# Generated by Django 5.1.6 on 2025-02-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='played_count',
            field=models.IntegerField(default=0),
        ),
    ]
