# Generated by Django 5.1.6 on 2025-02-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_played_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('player1', 'player2')},
        ),
    ]
