# Generated by Django 5.1.6 on 2025-04-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_losses_user_matched_played_count_user_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matched_played_count',
            field=models.IntegerField(default=1),
        ),
    ]
